dataset:
  train_images_root: ./data/train/
  val_images_root: ./data/test/
  train_path: ./data/train.txt
  test_path: ./data/test.txt
  val_path: ./data/test.txt
  classes_path: ./data/classes.txt
  batch_size: 16
  mean :
    - 0.485
    - 0.456
    - 0.406
  std:
    - 0.229
    - 0.224
    - 0.225
backbone:
  type: efficientnet_v2 # or `resnet50`
  frozen_layers: 4 # 7 for resnet50 is an appropiate choice
  input_size:
    - 256
    - 256
training:
  lr: 0.0001
  epochs: 2
  milestones: [2, 4, 6, 8]
evaluation:
  weights: ./outputs/weights/Exp_at_19_58_44_15_58_2023/best_model.pt
device: cuda
num_workers: 4

saved_dir: ./outputs/
validated_images_dir: ./result_images/