python: "3.10.5"
build_dependencies:
  - pip
dependencies:
  - torch==1.12.0+cu113
  - torchvision==0.13.0+cu113
  - black
  - flake8
  - matplotlib
  - mypy
  - opencv-python
  - Pillow
  - pyflakes
  - PyYAML
  - scikit-learn
  - scipy
  - tensorboard
  - types-PyYAML
